### ISSUE TITLE
Modules with optional dependencies breaking __init__

### ISSUE THREAD

**Issue by amandadumi** [chemreps/chemreps#65]
By including fingerprints in __init__.py file, it expects to find rdkit and breaks, despite it being an optional dependency.(See attached image from binder).

![Screenshot from 2020-02-05 10-12-12](https://user-images.githubusercontent.com/16597895/73867063-f7f79d80-4813-11ea-950e-6b0247367f7a.png)

A simple solution would be a try/except statement as below: 
```python
'''
Initializing of the main representation functions
'''
from . import utils
from . import bagger
from . import coulomb_matrix
from . import bag_of_bonds
from . import bat
from . import just_bonds
from . import dataset
try:
    import rdkit
    from . import fingerprints
except ImportError:
   print('Warning: Optional dependency rdkit not installed, the fingerprints representation will not be available')
```

I looked for formal ways within the setup.py process, but with no success.  Let me know what you guys think of this solution

**Comment by dlf57** [comment]
That is my bad for missing that when I added fingerprints in, sorry. Yeah, I think that would be a good solution.

**Comment by amandadumi** [comment]
It's not a big deal, I was using the binder as a reference and came across this. Speaking of binder, do we want to find a solution to having Conda install rdkit for the morgan fingerprint example notebook?  There may be another solution too, but that's not apparent to me.
