### ISSUE TITLE
Continuous Integration Changes

### ISSUE THREAD

**Issue by amandadumi** [chemreps/chemreps#76]
Considering the pricing model changes for Travis-CI, what does everyone feel about transitioning to Github Actions? Although there will probably still be a few bugs since its much newer, I use this for another project and have been happy thus far.

**Comment by dlf57** [comment]
What's going on with Travis? Sorry, I've been out of the loop lately. I believe my boss said they're using github actions for avogadro. I'd be fine switching over if people wanted to.

**Comment by shivupa** [comment]
Credit based pricing model https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by shivupa** [comment]
Also yeah amanda and Dr. Hutchison have been providing advice as cclib was moving to github actions. It seems nice and easy to use. I'm all for it!

**Comment by dlf57** [comment]
Sounds good to me then!

**Comment by amandadumi** [comment]
Perfect, I will try to do this over the weekend then! and hopefully get back to incorporating new representations too :)

**Comment by shivupa** [comment]
Closed via #77
